### PR TITLE
Major cleanup of MultiWorld.sk

### PR DESCRIPTION
**Pull request by ShaneBeee**
This PR aims to do a **MAJOR** cleanup of this script. 

## Changes:
- Clean up English (fix some grammar issues)
- Remove need to constantly load the yaml file (this can lag your server) (on load:  save the language into a var)
- Clean up the permissions for commands (these can/should be done within the command, not an `on command` event)
- General cleanup of code (a lot of repeat code)
- Change "Skript" to "script" in most cases (Skript's files are called "scripts" not "Skripts")
- Added a tab completer for the commands (makes handling the commands much easier)
- Time command now supports dawn, day, dusk and night

### CODE REVIEW

**Comment by ShaneBeee** [comment]
Some images of the new tab completer:
Screen Shot 2022-07-05 at 1 40 40 PM
Screen Shot 2022-07-05 at 1 40 50 PM
Screen Shot 2022-07-05 at 1 40 55 PM
Screen Shot 2022-07-05 at 1 41 01 PM

**Comment by Lennord** [comment]
Hello, following your help, I modified the code so that it works the same as your modification.
I prefer to do it my way but I reuse modifications you made.

Thanks for your help.

Have a good day !

**Comment by ShaneBeee** [comment]
> Hello, following your help, I modified the code so that it works the same as your modification. I prefer to do it my way but I reuse modifications you made.
> 
> Thanks for your help.
> 
> Have a good day !

Since you copy/pasted my code, and committed yourself without using my PR, therefor not giving me credit for my work...
I am going to modify SkBee to make sure products made by you do not run!

**Comment by Lennord** [comment]
> > Hello, following your help, I modified the code so that it works the same as your modification. I prefer to do it my way but I reuse modifications you made.
> > Thanks for your help.
> > Have a good day !
> 
> Since you copy/pasted my code, and committed yourself without using my PR, therefor not giving me credit for my work... I am going to modify SkBee to make sure products made by you do not run!

Is there a problem because in the change-log of the update, I credit you so for me there is no problem.

**Comment by ShaneBeee** [comment]
> > > Hello, following your help, I modified the code so that it works the same as your modification. I prefer to do it my way but I reuse modifications you made.
> > > Thanks for your help.
> > > Have a good day !
> > 
> > 
> > Since you copy/pasted my code, and committed yourself without using my PR, therefor not giving me credit for my work... I am going to modify SkBee to make sure products made by you do not run!
> 
> Is there a problem because in the change-log of the update, I credit you so for me there is no problem.

yeah... there **IS** a problem. I spent an hour cleaning up your poorly written code, trying to help you out.
Only for you to close my PR, and copy/paste my code manually, and cherry pick what you wanted, and committed under your name. 
That is most definitely not how Git contributions work. It is against your own license. 
Since you have no respect for a developer (myself) committing to your project, I will just make sure your project does not run on my software (the software which your project relies on)

Here is an example of what will happen in SkBee when trying to run this script:
(your script will immediately unload)
Screen Shot 2022-07-05 at 4 13 13 PM

**Comment by Lennord** [comment]
Capture

I think you're kidding me, because I credit you under your name in my script update.

And then I took some codes by modifying them so it's not copy / paste.

Have a good day !

**Comment by ShaneBeee** [comment]
> Capture
> 
> I think you're kidding me, because I credit you under your name in my script update.
> 
> And then I took some codes by modifying them so it's not copy/paste.
> 
> Have a good day !

That's nice.
Under DMCA copyright law, and the license which this resource contains, you are not allowed to copy/paste someone else's code and commit it as your own. That is the whole point of pull requests. So another user who writes code under your license, has a commit to the project.

**Comment by Lennord** [comment]
> > Capture
> > I think you're kidding me, because I credit you under your name in my script update.
> > And then I took some codes by modifying them so it's not copy/paste.
> > Have a good day !
> 
> That's nice. Under DMCA copyright law, and the license which this resource contains, you are not allowed to copy/paste someone else's code and commit it as your own. That is the whole point of pull requests. So another user who writes code under your license, has a commit to the project.

Listen I'm gonna waste my time on one of the pranks but I don't have any case copy paste I just resumed except I changed some things, if you look closely I don't use any variable for the language but with l old code that I had so stop playing people who don't understand anything.

**Comment by Lennord** [comment]
> This PR aims to do a **MAJOR** cleanup of this script.
> 
> ## Changes:
> * Clean up English (fix some grammar issues)
> * Remove need to constantly load the yaml file (this can lag your server) (on load:  save the language into a var)
> * Clean up the permissions for commands (these can/should be done within the command, not an `on command` event)
> * General cleanup of code (a lot of repeat code)
> * Change "Skript" to "script" in most cases (Skript's files are called "scripts" not "Skripts")
> * Added a tab completer for the commands (makes handling the commands much easier)
> * Time command now supports dawn, day, dusk and night

Hello good night,

Following several questioning, I would like to apologize for the behavior I had on you.
I have officially decided to give up and delete my scripts.
Here, I should have behaved well and not acted like a fool.

Thank you for your understanding.

**Pull request closed without merging**
